# Generated by Django 5.0.6 on 2025-09-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='platform',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='from_name',
            field=models.CharField(blank=True, help_text='Enter Form Name', max_length=100),
        ),
    ]
