# Generated by Django 5.0.6 on 2025-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_remove_emailtemplate_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='template_id',
            field=models.CharField(db_index=True, default=1, editable=False, help_text='Unique ID for searching this template.', max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
