# Generated by Django 5.0.6 on 2025-10-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_templateusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateusage',
            name='used_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
