# Generated by Django 5.0.6 on 2025-09-17 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalizedtag',
            options={'verbose_name': 'Personalized Tag Set', 'verbose_name_plural': 'Personalized Tag Sets'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='personalizedtag',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='trackingparamset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trackingparamset',
            name='name',
        ),
        migrations.AddField(
            model_name='trackingparamset',
            name='platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.platform'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trackingparamset',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='personalizedtag',
            constraint=models.UniqueConstraint(fields=('user', 'platform'), name='unique_user_platform_tag'),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_user_platform'),
        ),
    ]
