# Generated by Django 5.0.6 on 2025-09-27 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_trackingparamset_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlink',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='catalog.offer'),
        ),
        migrations.AlterField(
            model_name='offerlink',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
