# Generated by Django 5.0.6 on 2025-09-27 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_offerlink_offer_alter_offerlink_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlink',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='catalog.offer'),
        ),
    ]
